Hostname "collectd"
FQDNLookup false

Interval 0.2

LoadPlugin logfile

<Plugin logfile>
	LogLevel "info"
	File STDOUT
	Timestamp true
	PrintSeverity true
</Plugin>

LoadPlugin cpu
<Plugin cpu>
	ValuesPercentage True
	ReportByState True
	ReportByCpu True
</Plugin>

# the regex is matched against the full command line
LoadPlugin processes
<Plugin processes>
  ProcessMatch "collectd" "/bin/collectd( |$)"
  # resource_monitor_node and resource_diagnostics_updater_node are both loaded in this
  # container, so they share one process and cannot be measured separately
  ProcessMatch "resource_monitor_container" "__node:=resource_monitor_container( |$)"
</Plugin>

LoadPlugin df
<Plugin df>
  MountPoint "/"
  MountPoint "/hostfs"
  IgnoreSelected false
  LogOnce true
</Plugin>

LoadPlugin disk
<Plugin disk>
  Disk "/(loop)/"
  IgnoreSelected true
</Plugin>

LoadPlugin memory

LoadPlugin thermal

PluginDir "/ros_ws/build/collectd_socket_writer"
LoadPlugin collectd_socket_writer
<Plugin collectd_socket_writer>
  SocketPath "/tmp/telegraf.sock"
</Plugin>
